DROP SCHEMA IF EXISTS 給与 CASCADE;
CREATE SCHEMA 給与;

CREATE SEQUENCE 給与.従業員ID;
CREATE TABLE IF NOT EXISTS 給与.従業員
(
    従業員ID INTEGER PRIMARY KEY ,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE 給与.就業時間ID;
CREATE TABLE IF NOT EXISTS 給与.就業時間
(
    従業員ID INTEGER NOT NULL ,
    就業時間ID INTEGER NOT NULL ,
    勤務日 DATE NOT NULL ,
    開始日時 TIMESTAMP NOT NULL ,
    終了日時 TIMESTAMP NOT NULL ,
    休憩時間 INTEGER NOT NULL ,
    深夜休憩時間 INTEGER NOT NULL ,
    休日 VARCHAR(3) NOT NULL ,
    登録日時 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (従業員ID ,勤務日) ,
    FOREIGN KEY (従業員ID) REFERENCES 給与.従業員 (従業員ID)
);